let SEASON_SENIOR_A = [
  // Jornada 1
  {
    imgURL: "public/img/escudos/argual.png",
    date: "Sep 05, 2026 21:00:00",
    shortDate: "05/09/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAARGUAL",
  },
  // Copa de la Reina - 1ª Eliminatoria
  {
    imgURL: "public/img/escudos/samper.png",
    date: "Sep 09, 2026 21:00:00",
    shortDate: "09/09/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#COPADELAREINA",
  },
  // Jornada 2
  {
    imgURL: "public/img/escudos/sporting_huelva.png",
    date: "Sep 13, 2026 00:00:00",
    shortDate: "13/09/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAHUELVA",
  },
  // Jornada 3
  {
    imgURL: "public/img/escudos/almeria.png",
    date: "Sep 20, 2026 00:00:00",
    shortDate: "20/09/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAALMERIA",
  },
  // Jornada 4
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Sep 27, 2026 00:00:00",
    shortDate: "27/09/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Jornada 5
  {
    imgURL: "public/img/escudos/betis.png",
    date: "Oct 04, 2026 00:00:00",
    shortDate: "04/10/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIABETIS",
  },
  // Jornada 6
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Oct 11, 2026 00:00:00",
    shortDate: "11/10/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
  // Jornada 7
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Oct 25, 2026 00:00:00",
    shortDate: "25/10/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 8
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "Nov 01, 2026 00:00:00",
    shortDate: "01/11/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
  // Jornada 9
  {
    imgURL: "public/img/escudos/cacereno.png",
    date: "Nov 15, 2026 00:00:00",
    shortDate: "15/11/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACACERENO",
  },
  // Jornada 10
  {
    imgURL: "public/img/escudos/getafe.png",
    date: "Nov 22, 2026 00:00:00",
    shortDate: "22/11/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAGETAFE",
  },
  // Jornada 11
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Dec 06, 2026 00:00:00",
    shortDate: "06/12/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 12
  {
    imgURL: "public/img/escudos/union_viera.png",
    date: "Dec 13, 2026 00:00:00",
    shortDate: "13/12/26",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAVIERA",
  },
  // Jornada 13
  {
    imgURL: "public/img/escudos/fuensalida.png",
    date: "Dec 20, 2026 00:00:00",
    shortDate: "20/12/26",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAFUENSALIDA",
  },
  // Jornada 14
  {
    imgURL: "public/img/escudos/betis.png",
    date: "Jan 10, 2027 00:00:00",
    shortDate: "10/01/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIABETIS",
  },
  // Jornada 15
  {
    imgURL: "public/img/escudos/almeria.png",
    date: "Jan 17, 2027 00:00:00",
    shortDate: "17/01/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAALMERIA",
  },
  // Jornada 16
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Jan 31, 2027 00:00:00",
    shortDate: "31/01/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
  // Jornada 17
  {
    imgURL: "public/img/escudos/sporting_huelva.png",
    date: "Feb 07, 2027 00:00:00",
    shortDate: "07/02/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAHUELVA",
  },
  // Jornada 18
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Feb 14, 2027 00:00:00",
    shortDate: "14/02/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 19
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Feb 21, 2027 00:00:00",
    shortDate: "21/02/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 20
  {
    imgURL: "public/img/escudos/union_viera.png",
    date: "Mar 07, 2027 00:00:00",
    shortDate: "07/03/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAVIERA",
  },
  // Jornada 21
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Mar 14, 2027 00:00:00",
    shortDate: "14/03/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Jornada 22
  {
    imgURL: "public/img/escudos/cacereno.png",
    date: "Mar 21, 2027 00:00:00",
    shortDate: "21/03/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIACACERENO",
  },
  // Jornada 23
  {
    imgURL: "public/img/escudos/fuensalida.png",
    date: "Apr 04, 2027 00:00:00",
    shortDate: "04/04/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAFUENSALIDA",
  },
  // Jornada 24
  {
    imgURL: "public/img/escudos/getafe.png",
    date: "Apr 18, 2027 00:00:00",
    shortDate: "18/04/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAGETAFE",
  },
  // Jornada 25
  {
    imgURL: "public/img/escudos/argual.png",
    date: "Apr 25, 2027 00:00:00",
    shortDate: "25/04/27",
    isLocal: true,
    result: "",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAARGUAL",
  },
  // Jornada 26
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "May 02, 2027 00:00:00",
    shortDate: "02/05/27",
    isLocal: false,
    result: "",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
];

export default SEASON_SENIOR_A;