let SEASON_SENIOR_A = [
  // Jornada 1
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Sep 07, 2025 11:00:00",
    shortDate: "07/09/25",
    isLocal: false,
    result: "2-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Copa de la Reina - 1ª Eliminatoria
  {
    imgURL: "public/img/escudos/getafe.png",
    date: "Sep 10, 2025 20:00:00",
    shortDate: "10/09/25",
    isLocal: true,
    result: "5-3",
    mapsURL: "",
    liveURL: "",
    hashtag: "#COPADELAREINA",
  },
  // Jornada 2
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "Sep 14, 2025 17:00:00",
    shortDate: "14/09/25",
    isLocal: true,
    result: "2-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
  // Jornada 3
  {
    imgURL: "public/img/escudos/union_viera.png",
    date: "Sep 21, 2025 11:15:00",
    shortDate: "21/09/25",
    isLocal: true,
    result: "6-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAVIERA",
  },
  // Jornada 4
  {
    imgURL: "public/img/escudos/sporting_huelva.png",
    date: "Sep 28, 2025 12:00:00",
    shortDate: "28/09/25",
    isLocal: false,
    result: "2-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAHUELVA",
  },
  // Copa de la Reina - 2ª Eliminatoria
  {
    imgURL: "public/img/escudos/osasuna.png",
    date: "Oct 01, 2025 20:00:00",
    shortDate: "01/10/25",
    isLocal: true,
    result: "2-4",
    mapsURL: "",
    liveURL: "",
    hashtag: "#COPADELAREINA",
  },
  // Jornada 5
  {
    imgURL: "public/img/escudos/juan_grande.png",
    date: "Oct 04, 2025 16:00:00",
    shortDate: "04/10/25",
    isLocal: true,
    result: "5-0",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAJUANGRANDE",
  },
  // Jornada 6
  {
    imgURL: "public/img/escudos/betis.png",
    date: "Oct 11, 2025 16:00:00",
    shortDate: "11/10/25",
    isLocal: false,
    result: "2-1",
    mapsURL: "https://maps.app.goo.gl/mVdrt3KPEZkLWEEw7",
    liveURL: "",
    hashtag: "#OLYMPIABETIS",
  },
  // Jornada 7
  {
    imgURL: "public/img/escudos/getafe.png",
    date: "Oct 19, 2025 17:00:00",
    shortDate: "19/10/25",
    isLocal: true,
    result: "1-0",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAGETAFE",
  },
  // Jornada 8
  {
    imgURL: "public/img/escudos/granada.png",
    date: "Nov 02, 2025 13:30:00",
    shortDate: "02/11/25",
    isLocal: false,
    result: "2-1",
    mapsURL: "https://maps.app.goo.gl/2utQYFPpDFEWxUcm8",
    liveURL: "",
    hashtag: "#OLYMPIAGRANADA",
  },
  // Jornada 9
  {
    imgURL: "public/img/escudos/cacereno.png",
    date: "Nov 09, 2025 17:00:00",
    shortDate: "09/11/25",
    isLocal: true,
    result: "0-2",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIACACERENO",
  },
  // Jornada 10
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Nov 16, 2025 16:00:00",
    shortDate: "16/11/25",
    isLocal: false,
    result: "0-2",
    mapsURL: "https://maps.app.goo.gl/qF4zEC1GF2JULEAGA",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 11
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Nov 23, 2025 11:15:00",
    shortDate: "23/11/25",
    isLocal: true,
    result: "3-1",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
  // Jornada 12
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Dec 07, 2025 11:45:00",
    shortDate: "07/12/25",
    isLocal: false,
    result: "6-1",
    mapsURL: "https://maps.app.goo.gl/HLupNe9CSypHsSPT8",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 13
  {
    imgURL: "public/img/escudos/sport_extremadura.png",
    date: "Dec 14, 2025 17:00:00",
    shortDate: "14/12/25",
    isLocal: true,
    result: "1-0",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAEXTREMADURA",
  },
  // Jornada 14
  {
    imgURL: "public/img/escudos/juan_grande.png",
    date: "Jan 11, 2026 13:00:00",
    shortDate: "11/01/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/bjUYGRdDf3hXQwnv8",
    liveURL: "",
    hashtag: "#OLYMPIAJUANGRANDE",
  },
  // Jornada 15
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Jan 18, 2026 11:15:00",
    shortDate: "18/01/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Jornada 16
  {
    imgURL: "public/img/escudos/betis.png",
    date: "Feb 01, 2026 00:00:00",
    shortDate: "01/02/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIABETIS",
  },
  // Jornada 17
  {
    imgURL: "public/img/escudos/union_viera.png",
    date: "Feb 08, 2026 00:00:00",
    shortDate: "08/02/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/mBWUaD5pZk2CvFyD9",
    liveURL: "",
    hashtag: "#OLYMPIAVIERA",
  },
  // Jornada 18
  {
    imgURL: "public/img/escudos/granada.png",
    date: "Feb 15, 2026 00:00:00",
    shortDate: "15/02/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAGRANADA",
  },
  // Jornada 19
  {
    imgURL: "public/img/escudos/getafe.png",
    date: "Feb 22, 2026 00:00:00",
    shortDate: "22/02/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/Jkpre5c8snx4x3No7",
    liveURL: "",
    hashtag: "#OLYMPIAGETAFE",
  },
  // Jornada 20
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "Mar 08, 2026 00:00:00",
    shortDate: "08/03/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/mh1sfUMN5X9jHYQZ7",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
  // Jornada 21
  {
    imgURL: "public/img/escudos/sporting_huelva.png",
    date: "Mar 15, 2026 00:00:00",
    shortDate: "15/03/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAHUELVA",
  },
  // Jornada 22
  {
    imgURL: "public/img/escudos/sport_extremadura.png",
    date: "Mar 22, 2026 00:00:00",
    shortDate: "22/03/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/cSQRT7D8gWx5XYT86",
    liveURL: "",
    hashtag: "#OLYMPIAEXTREMADURA",
  },
  // Jornada 23
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Mar 29, 2026 00:00:00",
    shortDate: "29/03/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 24
  {
    imgURL: "public/img/escudos/cacereno.png",
    date: "Apr 12, 2026 00:00:00",
    shortDate: "12/04/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/JbJJG5XoXQx4vMJg6",
    liveURL: "",
    hashtag: "#OLYMPIACACERENO",
  },
  // Jornada 25
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Apr 19, 2026 00:00:00",
    shortDate: "19/04/26",
    isLocal: true,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/d2WLLm51F5Qv8iQJA",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 26
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Apr 26, 2026 00:00:00",
    shortDate: "26/04/26",
    isLocal: false,
    result: "-",
    mapsURL: "https://maps.app.goo.gl/RHeKBiLuskCaBj3F9",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
];

export default SEASON_SENIOR_A;
